apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ss-api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "soil-sense-1"
  labels:
    app: ss-api-ingress
spec:
  backend:
    serviceName: ss-api-service
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ss-api-service
  name: ss-api-service
spec:
  type: NodePort
  ports:
  - name: "3030"
    port: 80
    targetPort: 3030
  selector:
    app: ss-api
