version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './endpoints:/usr/src/app/endpoints'
    ports:
      - 3030:3030
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
