version: '3.7'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    environment:
      - API_USERNAME=andrew
      - API_PASSWORD=password
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
#    volumes:
#      - ./endpoints:/app/endpoints
    ports:
      - 3030:3030
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=development
      - DATABASE_DEV_URL=postgresql://postgres:password@db/postgres
      - DATABASE_TEST_URL=postgresql://postgres:password@localhost/postgres
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
